int miVariable = 1;
String textoPrimeraPantalla;
String textoSegundaPantalla;
String textoTerceraPantalla;
PImage challenger;
PImage titanic;
PImage avion;
boolean primeraPantalla = true;
boolean segundaPantalla = false;
boolean terceraPantalla = false;
int tiempoInicial;
int posicionTextoX = 0;
int posicionTextoY = height;
int tiempoSegundaPantalla = 34000;
float velocidadTextoSegundaPantalla = 1;
int tiempoInicioSegundaPantalla;
PImage botonreinicio;
float botonWidth = 100;  
float botonHeight = 50; 
float botonX;  
float botonY;  
